name: Docker Image CI
env:
  CLUSTER_NAME: multi-client-cluster
  CLUSTER_RESOURCE_GROUP: aks-cluster
  NAMESPACE: default
  APP_NAME: multi-client-cluster

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Login to Docker
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      
    - name: Build the Dev Docker image
      run: docker build -f ./client/Dockerfile.dev -t sanyaaxel/multi-docker-client-test ./client
      
    - name: Run Tests
      run: docker run -e CI=true sanyaaxel/multi-docker-client-test npm test -- --coverage

    - name: Build the Prod Docker Client image
      run: docker build -t sanyaaxel/multi-docker-client:${{ github.sha }} ./client
    - name: Build the Prod Docker API image
      run: docker build -t sanyaaxel/multi-docker-api:${{ github.sha }} ./server
    - name: Build the Prod Docker Worker image
      run: docker build -t sanyaaxel/multi-docker-worker :${{ github.sha }} ./worker
    - name: Build the Prod Docker Nginx image
      run: docker build -t sanyaaxel/multi-docker-nginx:${{ github.sha }} ./nginx

    - name: Publish Client
      run: docker push sanyaaxel/multi-docker-client:${{ github.sha }}
    - name: Publish API
      run: docker push sanyaaxel/multi-docker-api:${{ github.sha }}
    - name: Publish Worker
      run: docker push sanyaaxel/multi-docker-worker:${{ github.sha }}
    - name: Publish Nginx
      run: docker push sanyaaxel/multi-docker-nginx:${{ github.sha }}

  # Create image pull secret for ACR
    - uses: azure/k8s-deploy@v1
      with:
        manifests: |
          ${{ github.workspace }}/k8s
        namespace: ${{ env.NAMESPACE }}
